@startuml sap-theme

skinparam defaultFontName "Helvetica"
skinparam {
  
  FontStyle normal
  FontColor #333333
  FontSize 12

  BackgroundColor transparent
  DefaultBackgroundColor #F5F5F5
  CanvasBackgroundColor #FFFFFF

  
  Shadowing false

  ComponentBackgroundColor #FFFFFF
  ComponentBorderColor #0070F2
  ComponentBorderThickness 1
  ComponentFontColor #333333
  ComponentFontSize 12
  ComponentFontStyle bold
  ComponentStereotypeFontSize 10
  
  

  PackageBackgroundColor #EBF8FF
  PackageBorderColor #0070F2
  PackageBorderThickness 1
  PackageFontColor #333333
  PackageStyle frame 

  LineType ortho
  ArrowFontColor #333333
  ArrowFontSize 10
  ArrowColor #0070F2
  ArrowThickness 1
  
  NodeBackgroundColor #208bde
  NodeBorderColor #666666
  NodeFontColor #333333

  TitleFontColor #0D32B2
  TitleFontSize 16
  TitleFontStyle bold
  
}

skinparam monochrome false
skinparam classAttributeIconSize 0
skinparam padding 2
skinparam roundCorner 8

@enduml
